default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.2"
    hooks:
      - id: autopep8
        file: app/modules/lambda/serverless/
        args: [--diff, "--ignore=E501,W503,E203"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--count, "--ignore=E501,W503,E203,F722"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
