"""add_col

Revision ID: b3a0b3dbb63f
Revises: 3a2be67dba9c
Create Date: 2024-06-19 13:22:29.508026

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3a0b3dbb63f"
down_revision: Union[str, None] = "3a2be67dba9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mail_message", sa.Column("to_email", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mail_message", "to_email")
    # ### end Alembic commands ###
